export const GET_BOOKING ="GET_BOOKING";
export const ADD_BOOKING ="ADD_BOOKING";
export const DELETE_BOOKING ="DELETE_BOOKING";
export const UPDATE_BOOKING ="UPDATE_BOOKING";
export const CLEAR_CURRENT ="CLEAR_CURRENT";

export const SET_CURRENT ="SET_CURRENT";
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS  = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = "PROFILE_ERROR"
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
